### ISSUE TITLE
About iBom Capacitor Value Error

### ISSUE THREAD

**Issue by yungshan75424** [nataliethenerd/AGB_ReverseEngineer#1]
Hello, I noticed that the capacitance values for a few capacitors seem to be incorrect. Could you please correct them in the Ibom display? Thank you.

C17 should be 1uF.
C18~C20 should be 100pF.
However, in the Ibom:
C17, C18, and C19 are listed as 100pF,
and C20 is listed as 0.1uF, which seems to be incorrect.

For your reference, on page 18 of the attached document, at the top left corner, C17 is marked as 104 (0.1uF), and C18~C20 are marked as 101 (100pF).

https://drive.google.com/file/d/1IpKe2BRdcZLUURvhrvxnleMZf3MEI6tc/view

**Comment by nataliethenerd** [comment]
fixed! thank you!
